name: edtechschool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  get: ^4.7.2
  intl: any
  flutter_svg: ^2.0.7
  http: ^1.2.2
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  flutter_secure_storage: ^9.2.4
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:

    - assets/bigLogoEn.svg
    - assets/bigLogoKh.svg
    - assets/logoKh.svg
    - assets/logoEn.svg
    - assets/profile.jpg
    - assets/tiem_logo.svg
    - assets/Group.svg
    - assets/data/commune.json
    - assets/data/district.json
    - assets/data/province.json
    - assets/data/village.json