import 'package:get/get.dart';

class LangService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': <String, String>{
          'title': 'Hello',
          'change_lang': 'English',
          'welcome': 'welcome',
          'email': 'Email',
          'password': 'Password',
          'submit': 'Submit',
          'Attendance': 'Attendance',
          'Student Score': 'Student Score',
          'Permission': 'Permission',
          'Student_attendance': 'Student Attendance',
          'Score': 'Score',
          'My Profile': 'My Profile',
          'student': 'Student',
          'todaysClass': "Today's Class",
          'viewClasses': 'View Classes',
          'totalPermission': 'Total Permission',
          'absence': 'Absence',
          'addPermission': 'Add Permission',
          'feedback': 'Feedback',
          'home': 'Home',
          'logout': 'Logout',
          'myClasses': 'My Classes',
          'noClassesFound': 'No classes found.',
          'activeClasses': 'Active Classes',
          'totalStudent': 'Total Student',
          'noMatchingStudent': 'No matching student found.',
          'engNameLabel': 'Eng',
          'genderLabel': 'Gender',
          'phoneLabel': 'Phone',
          'scoreLabel': 'Score',
          'attendanceLabel': 'Attendance',
          'totalAttendanceScoreLabel': 'Total Attendance Score',
          'finalLabel': 'Final',
          'midtermLabel': 'Midterm',
          'quizLabel': 'Quiz',
          'noStudentData': 'No student data available',
          'errorLoadingAddress': 'Error loading address data',
          'villageLabel': ' Village',
          'communeLabel': ' Commune',
          'districtLabel': ' District',
          'provinceLabel': ' Province',
          'profileTitle': 'Profile',
          'gender': 'Gender',
          'phone': 'Phone',
          'address': 'Address',
          'notProvided': 'Not provided',
          'fatherName': "Father's Name",
          'motherName': "Mother's Name",
          'familyAddress': 'Family Address',
          'feedbackTitle': 'Feedback',
          'studentNotFound': 'Student not found.',
          'feedbackGreeting': 'Thank you for your feedback To Us!',
          'feedbackHint': 'Write feedback here...',
          'submitFeedback': 'Submit Feedback',
          'permissionStatusTitle': 'Permission Status',
          'noPermissionRequests': 'No permission requests found.',
          'reasonLabel': 'Reason',
          'dateLabel': 'Date',
          'noReason': 'No reason',
          'statusAccepted': 'Accepted',
          'statusRejected': 'Rejected',
          'statusPending': 'Pending',
          'attendanceTitle': 'Attendance',
          'studentAttendanceTitle': 'Student Attendance',
          'presentStatus': 'Present',
          'missingStatus': 'Missing',
          'addPermissionTitle': 'Add Permission',
          'selectClassLabel': '🏫 Select Class *',
          'selectClassHint': 'Select a class',
          'selectClassValidator': 'Please select a class',
          'chooseDateLabel': '📅 Choose Date *',
          'chooseDateHint': 'Choose date',
          'dateTo': 'to',
          'reasonLabelWithEmoji': '📝Reason *',
          'reasonHint': 'Ex: Sick leave, Personal reasons',
          'reasonValidator': 'Please enter the reason',
          'submitButton': 'Submit',
          'invalidDateRangeError': 'Please select a valid date range',
          'endDateError': 'End date must be after start date',
          'class_practice': 'Class Practice',
          'work_book': 'Workbook',
          'home_work': 'Homework',
          'revision_test': 'Revision Test',
          'presentation': 'Presentation',
          'assignment_score': 'Assignment Score',
          'final_exam': 'Final Exam',
          'total_score': 'Total Score',
          'attendance_score': 'Attendance Score',
          'all_my_classes': 'All my classes',

          // New Profile Page translations
          'dateOfBirth': 'Date of Birth',
          'familyDetails': 'Family Details',
          'birthDetails': 'Birth Details',
          'birthplace': 'Birthplace',
          'documents': 'Documents',
          'documentType': 'Document Type',
          'documentNumber': 'Document Number',
          'paymentStatus': 'Payment Status',
          'nextPaymentDue': 'Next payment due',
          'noUpcomingPayment': 'No upcoming payment',
          'paymentOverdue': 'Payment Overdue',
          'quickActions': 'Quick Actions',
          'attendancePermissions' : 'Attendance & Permissions',
          'areYouSureLogout': 'Are you sure you want to logout?',
          'yes': 'Logout',
          'no': 'Cancel',
  'myPermissions': 'My Permissions',
  'noActiveClasses': 'No active classes found',
  'confirmDelete': 'Confirm Delete',
  'confirmDeleteMessage': 'Are you sure you want to delete this permission request?',
  'submittedSuccessfully': 'Permission submitted successfully.',
  'updatedSuccessfully': 'Permission updated successfully.',
  'deletedSuccessfully': 'Permission deleted successfully.',
  'failedToSubmit': 'Failed to submit permission.',
  'failedToDelete': 'Failed to delete permission.',
  'editButton': 'Edit',
  'deleteButton': 'Delete',
  'updateButton': 'Update',
        },
        'km': {
          'title': 'សួស្តី',
          'change_lang': 'ភាសាខ្មែរ',
          'welcome': 'សូមស្វាគមន៍',
          'email': 'អ៊ីម៉ែល',
          'password': 'ពាក្យសម្ងាត់',
          'submit': 'បញ្ជូន',
          'Attendance': 'វត្តមាន',
          'Student Score': 'ពិន្ទុសិស្ស',
          'Permission': 'ការសុំច្បាប់',
          'Student_attendance': 'វត្តមានសិស្ស',
          'Score': 'ពិន្ទុ',
          'My Profile': 'ប្រវត្តិរូបរបស់ខ្ញុំ',
          'student': 'សិស្ស',
          'todaysClass': 'ថ្នាក់ថ្ងៃនេះ',
          'viewClasses': 'មើលថ្នាក់រៀន',
          'totalPermission': 'ការសុំច្បាប់សរុប',
          'absence': 'អវត្តមាន',
          'addPermission': 'សុំច្បាប់',
          'feedback': 'មតិយោបល់',
          'home': 'ទំព័រដើម',
          'logout': 'ចាកចេញ',
          'myClasses': 'ថ្នាក់របស់ខ្ញុំ',
          'noClassesFound': 'រកមិនឃើញថ្នាក់ទេ។',
          'activeClasses': 'ថ្នាក់ដែលកំពុងដំណើរការ',
          'totalStudent': 'សិស្សសរុប',
          'noMatchingStudent': 'រកមិនឃើញសិស្សដែលត្រូវគ្នាទេ។',
          'engNameLabel': 'អង់គ្លេស',
          'genderLabel': 'ភេទ',
          'phoneLabel': 'ទូរស័ព្ទ',
          'scoreLabel': 'ពិន្ទុ',
          'attendanceLabel': 'វត្តមាន',
          'totalAttendanceScoreLabel': 'ពិន្ទុវត្តមានសរុប',
          'finalLabel': 'វគ្គផ្តាច់ព្រ័ត្រ',
          'midtermLabel': 'ពាក់កណ្តាលអាណត្តិ',
          'quizLabel': 'កម្រងសំណួរ',
          'noStudentData': 'គ្មានទិន្នន័យសិស្ស',
          'errorLoadingAddress': 'កំហុសក្នុងការផ្ទុកទិន្នន័យអាសយដ្ឋាន',
          'villageLabel': 'ភូមិ',
          'communeLabel': 'ឃុំ',
          'districtLabel': 'ស្រុក',
          'provinceLabel': 'ខេត្ត',
          'profileTitle': 'ប្រវត្តិរូប',
          'gender': 'ភេទ',
          'phone': 'ទូរស័ព្ទ',
          'address': 'អាសយដ្ឋាន',
          'notProvided': 'មិនបានផ្តល់',
          'fatherName': 'ឈ្មោះឪពុក',
          'motherName': 'ឈ្មោះម្តាយ',
          'familyAddress': 'អាសយដ្ឋានគ្រួសារ',
          'feedbackTitle': 'មតិកែលម្អ',
          'studentNotFound': 'រកមិនឃើញសិស្សទេ។',
          'feedbackGreeting': 'សូម​អរគុណ​សម្រាប់​មតិ​របស់​អ្នក​មក​កាន់​យើង!',
          'feedbackHint': 'សរសេរមតិនៅទីនេះ...',
          'submitFeedback': 'ដាក់ស្នើមតិកែលម្អ',
          'permissionStatusTitle': 'ស្ថានភាពការអនុញ្ញាត',
          'noPermissionRequests': 'រកមិនឃើញសំណើសុំការអនុញ្ញាតទេ។',
          'reasonLabel': 'មូលហេតុ',
          'dateLabel': 'កាលបរិច្ឆេទ',
          'noReason': 'គ្មានមូលហេតុ',
          'statusAccepted': 'បានយល់ព្រម',
          'statusRejected': 'បានបដិសេធ',
          'statusPending': 'កំពុងរង់ចាំ',
          'attendanceTitle': 'វត្តមាន',
          'studentAttendanceTitle': 'វត្តមានសិស្ស',
          'presentStatus': 'មានវត្តមាន',
          'missingStatus': 'អវត្តមាន',
          'addPermissionTitle': 'បន្ថែមការអនុញ្ញាត',
          'selectClassLabel': '🏫 ជ្រើសរើសថ្នាក់ *',
          'selectClassHint': 'ជ្រើសរើសថ្នាក់',
          'selectClassValidator': 'សូមជ្រើសរើសថ្នាក់',
          'chooseDateLabel': '📅 ជ្រើសរើសកាលបរិច្ឆេទ *',
          'chooseDateHint': 'ជ្រើសរើសកាលបរិច្ឆេទ',
          'dateTo': 'ទៅ',
          'reasonLabelWithEmoji': '📝មូលហេតុ *',
          'reasonHint': 'ឧ: ការឈប់សម្រាកឈឺ, ហេតុផលផ្ទាល់ខ្លួន',
          'reasonValidator': 'សូមបញ្ចូលមូលហេតុ',
          'submitButton': 'បញ្ជូន',
          'invalidDateRangeError': 'សូមជ្រើសរើសកាលបរិច្ឆេទអោយបានត្រឹមត្រូវ',
          'endDateError': 'កាលបរិច្ឆេទបញ្ចប់ត្រូវតែនៅក្រោយកាលបរិច្ឆេទចាប់ផ្តើម',
          'class_practice': 'ការអនុវត្តក្នុងថ្នាក់',
          'work_book': 'សៀវភៅលំហាត់',
          'home_work': 'កិច្ចការផ្ទះ',
          'revision_test': 'ការប្រឡងកែប្រែ',
          'presentation': 'បទបង្ហាញ',
          'assignment_score': 'ពិន្ទុកិច្ចការ',
          'final_exam': 'ប្រឡងចុងឆមាស',
          'total_score': 'ពិន្ទុសរុប',
          'attendance_score': 'ពិន្ទុវត្តមាន',
          'all_my_classes': 'ថ្នាក់របស់ខ្ញុំទាំងអស់',

          // New Profile Page translations
          'dateOfBirth': 'ថ្ងៃខែឆ្នាំកំណើត',
          'familyDetails': 'ព័ត៌មានគ្រួសារ',
          'birthDetails': 'ព័ត៌មានកន្លែងកំណើត',
          'birthplace': 'កន្លែងកំណើត',
          'documents': 'ឯកសារ',
          'documentType': 'ប្រភេទឯកសារ',
          'documentNumber': 'លេខឯកសារ',
          'paymentStatus': 'ស្ថានភាពបង់ប្រាក់',
          'nextPaymentDue': 'ការបង់ប្រាក់បន្ទាប់',
          'noUpcomingPayment': 'មិនមានការបង់ប្រាក់បន្ទាប់',
          'paymentOverdue': 'ហួសកាលកំណត់បង់ប្រាក់',
          'quickActions': ' ផ្លូវកាត់',
          'attendancePermissions': 'វត្តមាន និងការអនុញ្ញាត',
          'areYouSureLogout': 'តើអ្នកពិតជាចង់ចាកចេញទេ?',
          'yes': 'ចាកចេញ',
          'no': 'បោះបង់',
  'myPermissions': 'ការសុំច្បាប់របស់ខ្ញុំ',
  'noActiveClasses': 'រកមិនឃើញថ្នាក់ដែលកំពុងដំណើរការទេ។',
  'confirmDelete': 'បញ្ជាក់ការលុប',
  'confirmDeleteMessage': 'តើអ្នកប្រាកដជាចង់លុបសំណើសុំការអនុញ្ញាតនេះទេ?',
  'submittedSuccessfully': 'បានដាក់ស្នើសុំការអនុញ្ញាតដោយជោគជ័យ។',
  'updatedSuccessfully': 'បានធ្វើបច្ចុប្បន្នភាពការអនុញ្ញាតដោយជោគជ័យ។',
  'deletedSuccessfully': 'បានលុបសំណើសុំការអនុញ្ញាតដោយជោគជ័យ។',
  'failedToSubmit': 'បរាជ័យក្នុងការដាក់ស្នើសុំការអនុញ្ញាត។',
  'failedToDelete': 'បរាជ័យក្នុងការលុបសំណើសុំការអនុញ្ញាត។',
  'editButton': 'កែប្រែ',
  'deleteButton': 'លុប',
  'updateButton': 'ធ្វើបច្ចុប្បនភាព',
        },
      };
}

